# Generated by Django 3.2.7 on 2021-09-14 00:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


def load_categories(apps, schema_editor):
    from django.core.management import call_command
    call_command('loaddata', 'contrib/fixtures/categories.json', verbosity=0)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('summary', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='article.category')),
            ],
        ),
        migrations.RunPython(load_categories),
    ]
