# Generated by Django 3.2.7 on 2021-09-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
