name: CI dev

on:
  pull_request:
    branches: master

jobs:
  test:
      name: Run tests
      runs-on: ubuntu-latest
      services:
        postgres:
          image: postgres
          env:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
          ports:
          - 5432:5432
      steps:
        - name: Checkout master
          uses: actions/checkout@v1
        - name: Run tests and lint
          run: |
            sudo apt-get install gcc
            python -m venv .venv
            source .venv/bin/activate
            pip install --upgrade pip
            pip install --upgrade setuptools
            pip install -r requirements.txt
            python manage.py migrate --no-input
            python manage.py test
            flake8 --max-line-length=120 --exclude .venv,.github,.idea,contrib